apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterctl-config
  annotations:
    meta.helm.sh/release-name: rancher-turtles
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  clusterctl.yaml: |
    providers:
    # Cluster API core provider
    - name:         "cluster-api"
      url:          "https://github.com/rancher-sandbox/cluster-api/releases/v1.12.2/core-components.yaml"
      type:         "CoreProvider"

    # Infrastructure providers
    - name:         "aws"
      url:          "https://github.com/rancher-sandbox/cluster-api-provider-aws/releases/v2.10.0/infrastructure-components.yaml"
      type:         "InfrastructureProvider"
    - name:         "azure"
      url:          "https://github.com/rancher-sandbox/cluster-api-provider-azure/releases/v1.22.0/infrastructure-components.yaml"
      type:         "InfrastructureProvider"
    - name:         "gcp"
      url:          "https://github.com/rancher-sandbox/cluster-api-provider-gcp/releases/v1.11.0/infrastructure-components.yaml"
      type:         "InfrastructureProvider"
    - name:         "vsphere"
      url:          "https://github.com/rancher-sandbox/cluster-api-provider-vsphere/releases/v1.14.0/infrastructure-components.yaml"
      type:         "InfrastructureProvider"
    - name:         "docker"
      url:          "https://github.com/kubernetes-sigs/cluster-api/releases/v1.12.2/infrastructure-components-development.yaml"
      type:         "InfrastructureProvider"

    # Bootstrap providers
    - name:         "kubeadm"
      url:          "https://github.com/rancher-sandbox/cluster-api/releases/v1.12.2/bootstrap-components.yaml"
      type:         "BootstrapProvider"
    - name:         "rke2"
      url:          "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.23.0/bootstrap-components.yaml"
      type:         "BootstrapProvider"

    # ControlPlane providers
    - name:         "kubeadm"
      url:          "https://github.com/rancher-sandbox/cluster-api/releases/v1.12.2/control-plane-components.yaml"
      type:         "ControlPlaneProvider"
    - name:         "rke2"
      url:          "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.23.0/control-plane-components.yaml"
      type:         "ControlPlaneProvider"

    # Addon providers
    - name:         "rancher-fleet"
      url:          "https://github.com/rancher/cluster-api-addon-provider-fleet/releases/v0.13.0/addon-components.yaml"
      type:         "AddonProvider"

    # Image overrides
    images:
      cluster-api:
        repository: "registry.rancher.com/rancher"
      control-plane-kubeadm:
        repository: "registry.rancher.com/rancher"
      bootstrap-kubeadm:
        repository: "registry.rancher.com/rancher"
      control-plane-rke2:
        repository: "registry.rancher.com/rancher"
      bootstrap-rke2:
        repository: "registry.rancher.com/rancher"
      infrastructure-aws:
        repository: "registry.rancher.com/rancher"
      infrastructure-azure:
        repository: "registry.rancher.com/rancher"
      infrastructure-gcp:
        repository: "registry.rancher.com/rancher"
      infrastructure-vsphere:
        repository: "registry.rancher.com/rancher"
      addon-rancher-fleet:
        repository: "registry.rancher.com/rancher"
