apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterctl-config
  annotations:
    meta.helm.sh/release-name: rancher-turtles
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  clusterctl.yaml: |
    providers:
    # Cluster API core provider
    - name:         "cluster-api"
      url:          "https://github.com/kubernetes-sigs/cluster-api/releases/v1.12.2/core-components.yaml"
      type:         "CoreProvider"
    images:
      cluster-api:
        repository: "rancher"
