apiVersion: v2
name: rancher-turtles
type: application
version: 0.0.0
appVersion: "0.0.0"
description: Rancher Turtles - Cluster API integration in Rancher.
home: https://github.com/rancher/turtles/
icon: https://raw.githubusercontent.com/rancher/turtles/main/logos/capi.svg
keywords:
- rancher
- cluster-api
- capi
- provisioning
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/managed: "true"
  catalog.cattle.io/display-name: Rancher Turtles
  catalog.cattle.io/kube-version: ">= 1.31.4-0 < 1.35.0-0"
  catalog.cattle.io/namespace: cattle-turtles-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/rancher-version: ">= 2.14.0-0 < 2.15.0-0"
  catalog.cattle.io/release-name: rancher-turtles
  catalog.cattle.io/scope: management
  catalog.cattle.io/type: cluster-tool
