# Default values for rancher-turtles-providers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# providers: Providers configuration.
providers:
  # addonFleet: Cluster API Add-on Provider for Fleet (CAAPF).
  addonFleet:
    # enabled: Enables the installation of this provider.
    enabled: true
    # namespace: The namespace where the provider manifests will be applied.
    namespace: fleet-addon-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
  # variables:
  #   ENV_VAR: "value"
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # bootstrapKubeadm: Kubeadm Bootstrap Provider.
  bootstrapKubeadm:
    # enabled: Enables the installation of this provider.
    enabled: false
    # namespace: The namespace where the provider manifests will be applied.
    namespace: capi-kubeadm-bootstrap-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
  # variables:
  #   ENV_VAR: "value"
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # bootstrapRKE2: RKE2 Bootstrap Provider.
  bootstrapRKE2:
    # enabled: Enables the installation of this provider.
    enabled: true
    # namespace: The namespace where the provider manifests will be applied.
    namespace: rke2-bootstrap-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
  # variables:
  #   ENV_VAR: "value"
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # controlplaneKubeadm: Kubeadm Control Plane Provider.
  controlplaneKubeadm:
    # enabled: Enables the installation of this provider.
    enabled: false
    # namespace: The namespace where the provider manifests will be applied.
    namespace: capi-kubeadm-control-plane-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
  # variables:
  #   ENV_VAR: "value"
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # controlplaneRKE2: RKE2 Control Plane Provider.
  controlplaneRKE2:
    # enabled: Enables the installation of this provider.
    enabled: true
    # namespace: The namespace where the provider manifests will be applied.
    namespace: rke2-control-plane-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
  # variables:
  #   ENV_VAR: "value"
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # infrastructureAWS: AWS Infrastructure Provider (CAPA).
  infrastructureAWS:
    # enabled: Enables the installation of this provider.
    enabled: false
    # namespace: The namespace where the provider manifests will be applied.
    namespace: capa-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
    variables:
      AWS_B64ENCODED_CREDENTIALS: ""
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # infrastructureAzure: Azure Infrastructure Provider (CAPZ).
  infrastructureAzure:
    # enabled: Enables the installation of this provider.
    enabled: false
    # namespace: The namespace where the provider manifests will be applied.
    namespace: capz-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
    variables:
      EXP_AKS_RESOURCE_HEALTH: "true"
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # infrastructureDocker: Docker Infrastructure Provider (CAPD).
  infrastructureDocker:
    # enabled: Enables the installation of this provider.
    enabled: false
    # namespace: The namespace where the provider manifests will be applied.
    namespace: capd-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
  # variables:
  #   ENV_VAR: "value"
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  # infrastructureGCP: GCP Infrastructure Provider (CAPG).
  infrastructureGCP:
    # enabled: Enables the installation of this provider.
    enabled: false
    # namespace: The namespace where the provider manifests will be applied.
    namespace: capg-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
    variables:
      EXP_CAPG_GKE: "true"
  # GCP_B64ENCODED_CREDENTIALS: GCP service account credentials
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
  infrastructureVSphere:
    # enabled: Enables the installation of this provider.
    enabled: false
    # namespace: The namespace where the provider manifests will be applied.
    namespace: capv-system
    # enableAutomaticUpdate: Allows the provider to be updated automatically whenever this chart is updated.
    enableAutomaticUpdate: true
  # version: Optional provider version
  # version: ""
  # features: Optional feature flags for this provider.
  # features:
  #   machinePool: false
  #   clusterResourceSet: false
  #   clusterTopology: false
  # variables: Optional environment variables exposed to the controller manager.
    variables:
      VSPHERE_USERNAME: ""
      VSPHERE_PASSWORD: ""
  # credentials: Optional Secret reference containing Rancher credentials
  # credentials:
  #   name: ""
  #   namespace: ""
  # configSecret: ConfigSecret is the object with name and namespace of the Secret providing the configuration variables for the current provider instance, like e.g. credentials.
  # configSecret:
  #   name: ""
  #   namespace: ""
  # fetchConfig: Override default artifact source via URL or OCI (specify one).
  # fetchConfig:
  #   url: "https://github.com/<org>/<repo>/releases"
  #   # oci: "ghcr.io/<org>/<artifact>:<tag>"
  # manager: Optional controller manager settings.
  # manager:
  #   syncPeriod: "5m"
