{{- if index .Values "cluster-api-operator" "cleanup" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-delete-job
  namespace: '{{ .Values.namespace }}'
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: post-delete-job-delete-webhooks
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: post-delete-job-webhook-cleanup
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
subjects:
  - kind: ServiceAccount
    name: post-delete-job
    namespace: '{{ .Values.namespace }}'
roleRef:
  kind: ClusterRole
  name: post-delete-job-delete-webhooks
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-api-operator-mutatingwebhook-cleanup
  namespace: '{{ .Values.namespace }}'
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: post-delete-job
      containers:
      - name: cluster-api-operator-mutatingwebhook-cleanup
        image: {{ .Values.shellImage }}
        command: ["kubectl"]
        args:
        - delete
        - mutatingwebhookconfigurations.admissionregistration.k8s.io
        - capi-mutating-webhook-configuration
        - --ignore-not-found=true
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-api-operator-validatingwebhook-cleanup
  namespace: '{{ .Values.namespace }}'
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: post-delete-job
      containers:
      - name: cluster-api-operator-validatingwebhook-cleanup
        image: {{ .Values.shellImage }}
        command: ["kubectl"]
        args:
        - delete
        - validatingwebhookconfigurations.admissionregistration.k8s.io
        - capi-validating-webhook-configuration
        - --ignore-not-found=true
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-api-operator-deployment-cleanup
  namespace: '{{ .Values.namespace }}'
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: post-delete-job
      restartPolicy: Never
      containers:
      - name: delete-capi-controller-manager
        image: {{ .Values.shellImage }}
        command: ["kubectl"]
        args:
        - delete
        - deployments.apps/capi-controller-manager
        - -n
        - {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
        - --ignore-not-found=true
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-api-operator-configmap-cleanup
  namespace: '{{ .Values.namespace }}'
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: post-delete-job
      restartPolicy: Never
      containers:
      - name: delete-capi-configmaps
        image: {{ .Values.shellImage }}
        command: ["kubectl"]
        args:
        - delete
        - configmaps
        - -n
        - {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
        - -l
        - managed-by.turtles.cattle.io=true
        - --ignore-not-found=true
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
{{- end }}
