---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: etcdmachinesnapshots.turtles-capi.cattle.io
spec:
  group: turtles-capi.cattle.io
  names:
    kind: ETCDMachineSnapshot
    listKind: ETCDMachineSnapshotList
    plural: etcdmachinesnapshots
    singular: etcdmachinesnapshot
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ETCDMachineSnapshot is the Schema for the ETCDMachineSnapshot
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ETCDMachineSnapshotSpec defines the desired state of EtcdMachineSnapshot
            properties:
              clusterName:
                type: string
              location:
                type: string
              machineName:
                type: string
            required:
            - clusterName
            type: object
            x-kubernetes-validations:
            - message: ETCD snapshot location can't be empty.
              rule: size(self.clusterName)>0
          status:
            description: EtcdSnapshotRestoreStatus defines observed state of EtcdSnapshotRestore
            properties:
              error:
                type: string
              phase:
                description: ETCDSnapshotPhase is a string representation of the phase
                  of the etcd snapshot
                type: string
              s3Snapshots:
                items:
                  properties:
                    creationTime:
                      description: CreationTime is the timestamp when the snapshot
                        was taken by etcd.
                      format: date-time
                      type: string
                    location:
                      type: string
                    name:
                      type: string
                  required:
                  - location
                  - name
                  type: object
                type: array
              snapshots:
                items:
                  properties:
                    creationTime:
                      description: CreationTime is the timestamp when the snapshot
                        was taken by etcd.
                      format: date-time
                      type: string
                    location:
                      type: string
                    machineName:
                      type: string
                    name:
                      type: string
                  required:
                  - location
                  - machineName
                  - name
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
