name: dependabot

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]
    branches:
      - dependabot/**
  push:
    branches:
      - dependabot/**
  workflow_dispatch:

permissions:
  contents: write # Allow to update the PR.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # tag=v3.5.0
      with:
        go-version: 1.23.9
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Update generated code
      run: make generate
    - name: Commit changes
      run: |
        git config --local user.email "49699333+dependabot[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        [[ -z "$(git status -s)" ]] || git commit -m "Update generated code" -s
        git push
