name: Janitor

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  azure-janitor:
    name: azure-janitor
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rancher/azure-janitor@v0.1.2
        with:
            resource-groups: highlander-e2e*
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
            client-id: ${{ secrets.AZURE_CLIENT_ID}}
            client-secret: ${{ secrets.AZURE_CLIENT_SECRET}}
            tenant-id: ${{ secrets.AZURE_TENANT_ID}}
            commit: true
  aws-janitor:
    if: success() || failure()
    name: aws-janitor
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Cleanup
        uses: rancher/aws-janitor@v0.2.0
        with:
          regions: eu-west-2
          commit: true
          ignore-tag: janitor-ignore
