
name: Legacy Release <v0.25.x

on:
  workflow_dispatch:
  push:
    tags:
      # Will only match if `<v0.25.x`
      - "v0.[0-9].*"
      - "v0.1[0-9].*"
      - "v0.2[0-4].*"

jobs:
  build-push-services:
    permissions:
      actions: read
      contents: write
      packages: write
      id-token: write
    strategy:
      matrix:
        destination: [ghcr, prod]
        include:
        - destination: ghcr
          registry: ghcr.io
          org: RANCHER_ORG
          image: IMAGE_NAME
          username: ${{ github.actor }}
          password: GITHUB_TOKEN
          secret_registry: false
        - destination: prod
          registry: PRIME_REGISTRY_ENDPOINT
          org: RANCHER_ORG
          image: IMAGE_NAME
          username: REGISTRY_USERNAME
          password: REGISTRY_PASSWORD
          secret_registry: true
    name: Release
    uses: ./.github/workflows/legacy-release.yml
    with:
      password: ${{ matrix.password }}
      username: ${{ matrix.username }}
      registry: ${{ matrix.registry }}
      org: ${{ matrix.org }}
      image: ${{ matrix.image }}
      tag: ${{ github.ref_name }}
      secret_registry: ${{ matrix.secret_registry }}
    secrets: inherit

  chart-release:
    name: Helm chart release
    uses: ./.github/workflows/chart-release.yml
    needs: [build-push-services]
    with:
      tag: ${{ github.ref_name }}
      org: ${{ vars.RANCHER_ORG }}
      image: ${{ vars.IMAGE_NAME }}
    secrets: inherit
