name: Build and Publish nightly Helm chart and Docker images

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight (UTC)
  workflow_dispatch: # Allow running manually on demand

env:
  TAG: v0.0.0-${{ github.sha }}
  RELEASE_TAG: v0.0.0-${{ github.sha }}
  CONTROLLER_IMAGE_VERSION: v0.0.0-${{ github.sha }}
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  REGISTRY: ghcr.io
  PROD_ORG: rancher

jobs:
  build-and-publish-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push docker images
      run: |
        make docker-build-and-push TAG=${{ env.TAG }} ORG=${{ env.PROD_ORG }}

  publish-helm-chart-ghcr:
    name: Publish Helm chart to GHCR
    needs:
    - build-and-publish-ghcr
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: Azure/setup-helm@v4
        with:
          version: 3.8.0
      - name: Build Helm chart
        run: make release-chart
      - name: Login to ghcr.io using Helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin
      - name: Publish Helm chart to GHCR
        env:
          GHCR_REPOSITORY: ${{ github.repository_owner }}/rancher-turtles-chart
        run: |
          helm push out/package/rancher-turtles-0.0.0-${{ github.sha }}.tgz oci://ghcr.io/${{ github.repository_owner }}/rancher-turtles-chart
      - name: Print helm install command
        run: |
          echo "Nightly build can be installed using the following command:"
          echo "helm install rancher-turtles oci://ghcr.io/${{ github.repository_owner }}/rancher-turtles-chart/rancher-turtles --version 0.0.0-${{ github.sha }}  -n rancher-turtles-system --create-namespace --wait"
