on:
  workflow_call:
    inputs:
      secret_registry:
        type: boolean
        description: All registry related inputs should be treated as secret values
        required: true

      image:
        type: string
        description: Static image value for the build

      password:
        type: string
        description: Registry password key to lookup in secrets
        required: true

      username:
        type: string
        description: Username for the registry login
        required: true

      registry:
        type: string
        description: Destination registry for image push
        required: true

      tag:
        type: string
        description: Tag for the built image
        required: true

      org:
        type: string
        description: Organization part of the image name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.image.outputs.digest }}
      image: ${{ steps.image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Build the image
        id: image
        uses: ./.github/workflows/release_build
        with:
          registry: ${{ inputs.secret_registry && secrets[inputs.registry] || inputs.registry }}
          org: ${{ vars[inputs.org] }}
          image: ${{ vars[inputs.image] }}
          tag: ${{ inputs.tag }}
          username: ${{ inputs.secret_registry && secrets[inputs.username] || inputs.username }}
          password: ${{ secrets[inputs.password] }}

  sign:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      actions: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Sign image with cosign
        uses: ./.github/workflows/release_sign
        with:
          image: ${{ inputs.secret_registry && secrets[inputs.registry] || inputs.registry }}/${{ vars[inputs.org] }}/${{ vars[inputs.image] }}
          digest: ${{ needs.build.outputs.digest }}
          identity: https://github.com/${{ vars[inputs.org] }}/turtles/.github/workflows/release.yml@${{ github.ref }}
          oids-issuer: https://token.actions.githubusercontent.com
          registry: ${{ inputs.secret_registry && secrets[inputs.registry] || inputs.registry }}
          username: ${{ inputs.secret_registry && secrets[inputs.username] || inputs.username }}
          password: ${{ secrets[inputs.password] }}
